sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.26.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  - sleep 30
  - docker-compose exec web npx sequelize db:migrate
  - docker-compose exec web npm test

after_sucess:
  - docker-compose down
  - docker build -t tsungtingdu/url-shortener-web ./web
  - docker build -t tsungtingdu/url-shortener-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tsungtingdu/url-shortener-web
  - docker push tsungtingdu/url-shortener-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: td-url-shortener
  env: TdUrlShortener-env
  bucket_name: elasticbeanstalk-ap-southeast-1-516245968608
  bucket_path: td-url-shortener
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY