version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports: 
      - "3306:3306"
    volumes: 
      - ./web/data/mysql:/var/lib/mysql
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      HOST: http://localhost:3000
      JWT_SECRET: development
    tty: true
    stdin_open: true
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes: 
      - ./nginx:/etc/nginx/nginx
    ports: 
      - '3000:3000'
    depends_on:
      - web