version: '3.8'
services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true